### ISSUE TITLE
全てOptionalなプロパティを持つオブジェクトが正しく変換されない

### ISSUE THREAD

**Issue by SIY1121** [aspida/openapi2aspida#132]
## Description

全てOptionalなプロパティを持つオブジェクトが、出力された型で全て必須になっています。

```yml
# openapi: 3.0.3

SampleObject:
  type: object
  properties:
    foo:
      type: string
    bar:
      type: integer
```

出力結果
```typescript
export type SampleObject = {
  foo: string
  bar: number
}
```

期待される結果
```typescript
export type SampleObject = {
  foo?: string
  bar?: number
}
```

仕様では全てのプロパティはデフォルトでOptionalです。
https://swagger.io/docs/specification/data-models/data-types/#ctxM:~:text=By%20default%2C%20all%20object%20properties%20are%20optional.

一応 `required` に空の配列を指定することで回避できると思われますが、上記仕様で空の配列は指定してはならないと明記されています。

## Environment

- **Package version:**
  
  `v0.16.1`
- **OS:**
  
  - [x] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
14.16.0
  ``
- **npm version:**
6.14.11
  ``

## Additional context
原因箇所はここだと思われます。
https://github.com/aspida/openapi2aspida/blob/1619112f38f5824afffcf1fbd92b91f3998cbd24/src/builderUtils/converters.ts#L62
