### ISSUE TITLE
リクエストボディのパラメータが File の配列にならない

### ISSUE THREAD

**Issue by myrear** [aspida/openapi2aspida#156]
## Description

リクエストボディにあるバイナリの配列が File の配列として出力されません。

```yaml
# openapi 3.0.1

SampleBody:
  type: object
  properties:
    files:
      type: array
      items:
        type: string
        format: binary
```

出力結果

```typescript
export type SampleBody = {
  files: File | ReadStream[]
}
```

期待される出力結果

```typescript
export type SampleBody = {
  files?: (File | ReadStream)[]
}
```

## Environment

- **Package version:**
  
  `v0.16.5`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v14.17.3`
- **npm version:**
  
  `v6.14.13`

## Additional context

おそらく原因となっている箇所はこちらです。
https://github.com/aspida/openapi2aspida/blob/master/src/builderUtils/converters.ts#L96

`BINARY_TYPE = '(File | ReadStream)'` とすると一応期待通りの動作になりました。
