### ISSUE TITLE
Incorrect TypeScript Type Generation for OpenAPI `allOf` and `oneOf` Combinations

### ISSUE THREAD

**Issue by mpyw** [aspida/openapi2aspida#251]
## Description

`openapi2aspida` seems to incorrectly transform OpenAPI schemas using `allOf` and `oneOf`. The issue is with combining common properties (defined with `allOf`) and selective properties (defined with `oneOf`) in TypeScript type.

### OpenAPI Spec

```yaml
MyObject:
  type: object
  allOf:
    - type: object
      properties:
        commonProperty:
          type: string
      required:
        - commonProperty
    - type: object
      oneOf:
        - type: object
          properties:
            optionA:
              type: string
          required:
            - optionA
        - type: object
          properties:
            optionB:
              type: number
          required:
            - optionB
```

### Expected Output

```ts
export type MyObject = {
  commonProperty: string;
} & (
  | {
      optionA: string;
    }
  | {
      optionB: number;
    }
);
```

### Actual Output

```ts
export type MyObject = {
  commonProperty: string;
} & {
  optionA: string;
} | {
  optionB: number;
};
```

## Environment

- **Package version:**
  `v0.23.2`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `20.6.1`
- **npm version:**
  
  `9.8.1`
