### ISSUE TITLE
Relative paths in `$ref` to external files are not resolved correctly

### ISSUE THREAD

**Issue by kazukinagata** [aspida/openapi2aspida#260]
## Description

When referencing split files with the same name located in different directories using relative paths, the issue arises at [this line](https://github.com/aspida/openapi2aspida/blob/main/src/resolveExternalRefs.ts#L41), where URLs are treated as duplicates. As a result, the correct type definitions are not generated.

Do you have plans to fix this issue? If not, I would be happy to submit a PR includes the necessary fixes and tests.

Thank you for this amazing library!

```sh
samples/nested-relative-refs/
├── index.yaml
├── models
│   ├── metadata.yaml
│   └── user.yaml
└── requests
    ├── metadata.yaml
    └── user.yaml
```

```yaml
# samples/nested/relative-refs/models/user.yaml
title: User
description: User model
type: object
xml:
  name: User
properties:
  name:
    type: string
  metadata:
    $ref: './metadata.yaml'
required:
  - name
  - metadata
```

```yaml
# samples/nested/relative-refs/requests/user.yaml
title: UserRequest
description: User request
type: object
xml:
  name: UserRequest
properties:
  name:
    type: string
  metadata:
    $ref: './metadata.yaml'
```

## Environment

- **Package version:**
  
  `v0.24.0`
- **OS:**
  
  - [x] Linux
  - [ ] Windows
  - [ ] macOS
- **Node.js version:**
  
  `18.20.4`
- **npm version:**
  
  `10.7.0`
